# Generated by Django 4.2.7 on 2026-01-11 22:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_venda_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Despesa Fixa',
                'verbose_name_plural': 'Categorias de Despesas Fixas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequencia', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=10)),
                ('data_vencimento', models.IntegerField(help_text='Dia do vencimento (1-31)')),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriadespesafixa')),
            ],
            options={
                'verbose_name': 'Despesa Fixa',
                'verbose_name_plural': 'Despesas Fixas',
                'ordering': ['categoria', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoDespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('data_referencia', models.DateField(help_text='Mês/ano de referência')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.despesafixa')),
            ],
            options={
                'verbose_name': 'Pagamento de Despesa Fixa',
                'verbose_name_plural': 'Pagamentos de Despesas Fixas',
                'ordering': ['-data_pagamento'],
                'unique_together': {('despesa', 'data_referencia')},
            },
        ),
    ]
